-- Only one of these presets can be used. 
-- Add milestones for a mod here if the mod is a major mod that changes the game a lot and would not work well combined with another major mod.
-- If the mod is small and could be combined with any major mod, add the milestones in preset_addons.lua instead.

-- The preset with the highest number of "required mods" matches will be selected. (e.g. Bob's and Angel's will be selected over just Bob's)
-- If the mod is compatible with a limited amount of other major mods, you can have a preset for combinations (e.g. There is an SE preset, a K2 preset, and a SE+K2 preset)

presets = {
    ["Vanilla"] = {
        required_mods = {},
        milestones = {
            {type="item",       name="automation-science-pack", quantity=1},
            {type="item",       name="logistic-science-pack",   quantity=1},
            {type="item",       name="military-science-pack",   quantity=1},
            {type="fluid",      name="petroleum-gas",           quantity=1},
            {type="item",       name="chemical-science-pack",   quantity=1},
            {type="item",       name="production-science-pack", quantity=1},
            {type="item",       name="utility-science-pack",    quantity=1},
            {type="technology", name="rocket-silo",             quantity=1},
            {type="item",       name="rocket-part",             quantity=100},
            {type="item",       name="space-science-pack",      quantity=1},
            {type="item",       name="locomotive",              quantity=1},
            {type="item",       name="construction-robot",      quantity=1},
            {type="item",       name="spidertron",              quantity=1},
            {type="item",       name="uranium-fuel-cell",       quantity=1},
            {type="item",       name="solar-panel",             quantity=1},
            {type="item",       name="solar-panel",             quantity=10000, next="x10"},
            {type="item",       name="automation-science-pack", quantity=10000, next="x10"},
            {type="item",       name="logistic-science-pack",   quantity=10000, next="x10"},
            {type="item",       name="military-science-pack",   quantity=10000, next="x10"},
            {type="item",       name="chemical-science-pack",   quantity=10000, next="x10"},
            {type="item",       name="production-science-pack", quantity=10000, next="x10"},
            {type="item",       name="utility-science-pack",    quantity=10000, next="x10"},
            {type="item",       name="space-science-pack",      quantity=10000, next="x10"},
            {type="kill",       name="medium-biter",            quantity=1},
            {type="kill",       name="big-biter",               quantity=1},
            {type="kill",       name="behemoth-biter",          quantity=1},
            {type="kill",       name="character",               quantity=1, next="x5"},
        }
    },


    ["Vanilla (Extended)"] = {
        required_mods = {},
        milestones = {
            {type="item",       name="automation-science-pack", quantity=1},
            {type="item",       name="logistic-science-pack",   quantity=1},
            {type="item",       name="military-science-pack",   quantity=1},
            {type="fluid",      name="petroleum-gas",           quantity=1},
            {type="item",       name="chemical-science-pack",   quantity=1},
            {type="item",       name="construction-robot",      quantity=1},
            {type="item",       name="production-science-pack", quantity=1},
            {type="item",       name="utility-science-pack",    quantity=1},
            {type="technology", name="rocket-silo",             quantity=1},
            {type="item",       name="rocket-part",             quantity=100},
            {type="item",       name="space-science-pack",      quantity=1},
            {type="item",       name="locomotive",              quantity=1},
            {type="item",       name="car",                     quantity=1},
            {type="item",       name="tank",                    quantity=1},
            {type="item",       name="spidertron",              quantity=1},
            {type="item",       name="uranium-fuel-cell",       quantity=1},
            {type="item",       name="solar-panel",             quantity=1},
            {type="item",       name="solar-panel",             quantity=1000, next="x10"},
            {type="item",       name="automation-science-pack", quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="production-science-pack", quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",    quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",      quantity=10000, next="x10"},
            {type="kill",       name="medium-biter",            quantity=1},
            {type="kill",       name="big-biter",               quantity=1},
            {type="kill",       name="behemoth-biter",          quantity=1},
            {type="kill",       name="behemoth-biter",          quantity=1000, next="x10"},
            {type="kill",       name="character",               quantity=1, next="x5"},
        }
    },


    ["Space Exploration (No Spoilers)"] = {
        required_mods = {"space-exploration"},
        milestones = {
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="se-rocket-launch-pad-silo-dummy-result-item", quantity=1, next="x10"},
            {type="technology", name="se-spaceship",                 quantity=1},
            {type="item",       name="se-vulcanite-block",           quantity=1},
            {type="item",       name="se-cryonite-rod",              quantity=1},
            {type="item",       name="se-vitamelange-roast",         quantity=1},
            {type="item",       name="se-beryllium-ingot",           quantity=1},
            {type="item",       name="se-holmium-ingot",             quantity=1},
            {type="item",       name="se-iridium-ingot",             quantity=1},
            {type="item",       name="se-naquium-ingot",             quantity=1},
            {type="item",       name="se-rocket-science-pack",       quantity=1},
            {type="item",       name="se-significant-data",          quantity=1},
            {type="item",       name="se-astronomic-science-pack-1", quantity=1},
            {type="item",       name="se-astronomic-science-pack-2", quantity=1},
            {type="item",       name="se-astronomic-science-pack-3", quantity=1},
            {type="item",       name="se-astronomic-science-pack-4", quantity=1},
            {type="item",       name="se-biological-science-pack-1", quantity=1},
            {type="item",       name="se-biological-science-pack-2", quantity=1},
            {type="item",       name="se-biological-science-pack-3", quantity=1},
            {type="item",       name="se-biological-science-pack-4", quantity=1},
            {type="item",       name="se-energy-science-pack-1",     quantity=1},
            {type="item",       name="se-energy-science-pack-2",     quantity=1},
            {type="item",       name="se-energy-science-pack-3",     quantity=1},
            {type="item",       name="se-energy-science-pack-4",     quantity=1},
            {type="item",       name="se-material-science-pack-1",   quantity=1},
            {type="item",       name="se-material-science-pack-2",   quantity=1},
            {type="item",       name="se-material-science-pack-3",   quantity=1},
            {type="item",       name="se-material-science-pack-4",   quantity=1},
            {type="item",       name="se-deep-space-science-pack-1", quantity=1},
            {type="item",       name="se-deep-space-science-pack-2", quantity=1},
            {type="item",       name="se-deep-space-science-pack-3", quantity=1},
            {type="item",       name="se-deep-space-science-pack-4", quantity=1},
            {type="technology", name="se-spaceship-victory",         quantity=1},
            {type="item",       name="se-significant-data",          quantity=1000, next="x10"},
            {type="kill",       name="medium-biter",                 quantity=1},
            {type="kill",       name="big-biter",                    quantity=1},
            {type="kill",       name="behemoth-biter",               quantity=1},
            {type="kill",       name="character",                    quantity=1, next="x5"},
        }
    },


    ["Krastorio 2"] = {
        required_mods = {"Krastorio2"},
        milestones = {
            {type="item",       name="basic-tech-card",              quantity=1},
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="fluid",      name="mineral-water",                quantity=1},
            {type="item",       name="silicon",                      quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="rare-metals",                  quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="imersite-powder",              quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="ai-core",                      quantity=1},
            {type="item",       name="space-science-pack",           quantity=1},
            {type="item",       name="matter-tech-card",             quantity=1},
            {type="fluid",      name="matter",                       quantity=1},
            {type="item",       name="advanced-tech-card",           quantity=1},
            {type="technology", name="kr-advanced-pickaxe",          quantity=1},
            {type="item",       name="singularity-tech-card",        quantity=1},
            {type="item",       name="kr-intergalactic-transceiver", quantity=1},
            {type="item",       name="basic-tech-card",              quantity=1000, next="x10"},
            {type="item",       name="automation-science-pack",      quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",      quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",           quantity=1000, next="x10"},
            {type="item",       name="matter-tech-card",             quantity=1000, next="x10"},
            {type="item",       name="advanced-tech-card",           quantity=1000, next="x10"},
            {type="item",       name="singularity-tech-card",        quantity=1000, next="x10"},
            {type="kill",       name="medium-biter",                 quantity=1},
            {type="kill",       name="big-biter",                    quantity=1},
            {type="kill",       name="behemoth-biter",               quantity=1},
            {type="kill",       name="character",                    quantity=1, next="x5"},
        }
    },


    ["Space Exploration + Krastorio 2 (No Spoilers)"] = {
        required_mods = {"space-exploration", "Krastorio2"},
        milestones = {
            {type="item",       name="basic-tech-card",              quantity=1},
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="item",       name="silicon",                      quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="se-rocket-launch-pad-silo-dummy-result-item", quantity=1, next="x10"},
            {type="technology", name="se-spaceship",                 quantity=1},
            {type="item",       name="se-vulcanite-block",           quantity=1},
            {type="item",       name="se-cryonite-rod",              quantity=1},
            {type="item",       name="se-vitamelange-roast",         quantity=1},
            {type="item",       name="se-beryllium-ingot",           quantity=1},
            {type="item",       name="se-holmium-ingot",             quantity=1},
            {type="item",       name="se-iridium-ingot",             quantity=1},
            {type="fluid",      name="mineral-water",                quantity=1},
            {type="item",       name="rare-metals",                  quantity=1},
            {type="item",       name="imersite-powder",              quantity=1},
            {type="item",       name="se-naquium-ingot",             quantity=1},
            {type="item",       name="se-rocket-science-pack",       quantity=1},
            {type="item",       name="space-science-pack",           quantity=1},
            {type="item",       name="se-significant-data",          quantity=1},
            {type="item",       name="se-astronomic-science-pack-1", quantity=1},
            {type="item",       name="se-astronomic-science-pack-2", quantity=1},
            {type="item",       name="se-astronomic-science-pack-3", quantity=1},
            {type="item",       name="se-astronomic-science-pack-4", quantity=1},
            {type="item",       name="se-biological-science-pack-1", quantity=1},
            {type="item",       name="se-biological-science-pack-2", quantity=1},
            {type="item",       name="se-biological-science-pack-3", quantity=1},
            {type="item",       name="se-biological-science-pack-4", quantity=1},
            {type="item",       name="se-energy-science-pack-1",     quantity=1},
            {type="item",       name="se-energy-science-pack-2",     quantity=1},
            {type="item",       name="se-energy-science-pack-3",     quantity=1},
            {type="item",       name="se-energy-science-pack-4",     quantity=1},
            {type="item",       name="se-material-science-pack-1",   quantity=1},
            {type="item",       name="se-material-science-pack-2",   quantity=1},
            {type="item",       name="se-material-science-pack-3",   quantity=1},
            {type="item",       name="se-material-science-pack-4",   quantity=1},
            {type="item",       name="se-deep-space-science-pack-1", quantity=1},
            {type="item",       name="se-deep-space-science-pack-2", quantity=1},
            {type="item",       name="se-deep-space-science-pack-3", quantity=1},
            {type="item",       name="se-deep-space-science-pack-4", quantity=1},
            {type="technology", name="kr-advanced-pickaxe",          quantity=1},
            {type="item",       name="ai-core",                      quantity=1},
            {type="item",       name="matter-tech-card",             quantity=1},
            {type="fluid",      name="matter",                       quantity=1},
            {type="item",       name="advanced-tech-card",           quantity=1},
            {type="item",       name="singularity-tech-card",        quantity=1},
            {type="item",       name="kr-intergalactic-transceiver", quantity=1},
            {type="technology", name="se-spaceship-victory",         quantity=1},
            {type="item",       name="se-significant-data",          quantity=1000, next="x10"},
            {type="kill",       name="medium-biter",                 quantity=1},
            {type="kill",       name="big-biter",                    quantity=1},
            {type="kill",       name="behemoth-biter",               quantity=1},
            {type="kill",       name="character",                    quantity=1, next="x5"},
        }
    },


    ["Bob's Mods (Without Bob's Tech)"] = {
        required_mods = {"bobplates", "bobelectronics"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},
            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="antron",                         quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            {type="item",       name="automation-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",           quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",             quantity=1000, next="x10"},
            {type="kill",       name="character",                      quantity=1, next="x5"},
        }
    },


    ["Bob's Mods"] = {
        required_mods = {"bobplates", "bobelectronics", "bobtech"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="science-pack-gold",              quantity=1},
            {type="item",       name="advanced-logistic-science-pack", quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},
            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="antron",                         quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            {type="item",       name="automation-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="science-pack-gold",              quantity=1000, next="x10"},
            {type="item",       name="advanced-logistic-science-pack", quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",           quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",             quantity=1000, next="x10"},
            {type="kill",       name="character",                      quantity=1, next="x5"},
        }
    },


    ["Angel's Industries"] = {
        required_mods = {"angelsindustries"},
        milestones = {
            {type="item",       name="automation-science-pack",   quantity=1},
            {type="item",       name="logistic-science-pack",     quantity=1},
            {type="item",       name="locomotive",                quantity=1},
            {type="item",       name="angels-construction-robot", quantity=1},
            {type="item",       name="military-science-pack",     quantity=1},
            {type="fluid",      name="gas-methane",               quantity=1},
            {type="item",       name="plastic-bar",               quantity=1},
            {type="item",       name="chemical-science-pack",     quantity=1},
            {type="item",       name="construction-robot",        quantity=1},
            {type="item",       name="sulfur",                    quantity=1},
            {type="fluid",      name="liquid-sulfuric-acid",      quantity=1},
            {type="item",       name="production-science-pack",   quantity=1},
            {type="item",       name="utility-science-pack",      quantity=1},
            {type="item",       name="rocket-fuel",               quantity=1},
            {type="technology", name="rocket-silo",               quantity=1},
            {type="item",       name="rocket-part",               quantity=100},
            {type="item",       name="space-science-pack",        quantity=1},
            {type="item",       name="token-bio",                 quantity=1},
            {type="item",       name="electronic-circuit",        quantity=1},
            {type="item",       name="advanced-circuit",          quantity=1},
            {type="item",       name="processing-unit",           quantity=1},
            {type="item",       name="angels-plate-titanium",     quantity=1},
            {type="item",       name="angels-plate-tungsten",     quantity=1},
            {type="item",       name="angels-crawler",            quantity=1},
            {type="item",       name="spidertron",                quantity=1},
            {type="item",       name="uranium-fuel-cell",         quantity=1},
            {type="item",       name="solar-panel",               quantity=1},
            {type="item",       name="crystal-full-harmonic",     quantity=1},
            {type="item",       name="automation-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",     quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",     quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",     quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",      quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",        quantity=1000, next="x10"},
            {type="kill",       name="character",                 quantity=2},
        }
    },


    ["Bob's and Angel's Mods"] = {
        required_mods = {"bobplates", "bobelectronics", "bobtech", "angelsindustries"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="science-pack-gold",              quantity=1},
            {type="item",       name="advanced-logistic-science-pack", quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},
            {type="item",       name="token-bio",                      quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},

            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},

            {type="fluid",      name="gas-methane",                    quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="sulfur",                         quantity=1},
            {type="fluid",      name="liquid-sulfuric-acid",           quantity=1},
            {type="fluid",      name="liquid-resin",                   quantity=1},
            {type="item",       name="solid-paper",                    quantity=1},

            {type="item",       name="rocket-fuel",                    quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            
            {type="item",       name="angels-construction-robot",      quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="angels-crawler",                 quantity=1},
            {type="item",       name="antron",                         quantity=1},

            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="angels-thorium-fuel-cell",       quantity=1},
            {type="item",       name="angels-deuterium-fuel-cell",     quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="crystal-full-harmonic",          quantity=1},

            {type="item",       name="automation-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="science-pack-gold",              quantity=1000, next="x10"},
            {type="item",       name="advanced-logistic-science-pack", quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",           quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",             quantity=1000, next="x10"},
            {type="kill",       name="character",                      quantity=1, next="x5"},
        }
    },


    ["Nullius"] = {
        required_mods = {"angelssmelting", "nullius"},
        milestones = {
            {type="item",       name="nullius-geology-pack",             quantity=1},
            {type="item",       name="nullius-climatology-pack",         quantity=1},
            {type="item",       name="nullius-mechanical-pack",          quantity=1},
            {type="item",       name="nullius-electrical-pack",          quantity=1},
            {type="item",       name="nullius-chemical-pack",            quantity=1},
            {type="item",       name="nullius-physics-pack",             quantity=1},
            {type="item",       name="nullius-astronomy-pack",           quantity=1},

            {type="item",       name="nullius-biochemistry-pack",        quantity=1},
            {type="item",       name="nullius-microbiology-pack",        quantity=1},
            {type="item",       name="nullius-botany-pack",              quantity=1},
            {type="item",       name="nullius-nematology-pack",          quantity=1},
            {type="item",       name="nullius-dendrology-pack",          quantity=1},
            {type="item",       name="nullius-ichthyology-pack",         quantity=1},
            {type="item",       name="nullius-zoology-pack",             quantity=1},

            {type="item",       name="nullius-iron-ingot",               quantity=1},
            {type="item",       name="nullius-plastic",                  quantity=1},
            {type="item",       name="nullius-glass",                    quantity=1},
            {type="item",       name="nullius-aluminum-ingot",           quantity=1},
            {type="item",       name="nullius-silicon-ingot",            quantity=1},
            {type="item",       name="nullius-steel-ingot",              quantity=1},
            {type="item",       name="nullius-fiberglass",               quantity=1},
            {type="item",       name="nullius-titanium-ingot",           quantity=1},
            {type="item",       name="nullius-copper-ingot",             quantity=1},

            {type="item",       name="nullius-processor-1",              quantity=1},
            {type="item",       name="nullius-processor-2",              quantity=1},
            {type="item",       name="nullius-processor-3",              quantity=1},

            {type="item",       name="nullius-terraforming-drone-brown", quantity=1},
            {type="item",       name="nullius-rocket",                   quantity=1},
            {type="item",       name="nullius-algaculture-drone",        quantity=1},
            {type="item",       name="nullius-horticulture-drone",       quantity=1},
            {type="item",       name="nullius-arboriculture-drone",      quantity=1},
            {type="item",       name="nullius-entomology-drone",         quantity=1},
            {type="item",       name="nullius-aquaculture-drone",        quantity=1},
            {type="item",       name="nullius-husbandry-drone",          quantity=1},
            {type="item",       name="nullius-guide-drone-copper-1",     quantity=1},
            {type="item",       name="nullius-guide-drone-uranium-1",    quantity=1},
            {type="item",       name="nullius-antimatter",               quantity=1},
            {type="item",       name="nullius-probe",                    quantity=1},
            {type="item",       name="nullius-probe",                    quantity=10},

            {type="item",       name="nullius-locomotive-1",             quantity=1},
            {type="item",       name="nullius-logistic-bot-1",           quantity=1},
            {type="item",       name="cliff-explosives",                 quantity=1},
            {type="item",       name="nullius-android-1",                quantity=1},
            {type="item",       name="nullius-android-2",                quantity=1},
            {type="item",       name="nullius-mecha",                    quantity=1},

            {type="item",       name="nullius-wind-turbine-1",           quantity=1},
            {type="item",       name="nullius-solar-collector-1",        quantity=1},
            {type="item",       name="nullius-solar-panel-1",            quantity=16},
            {type="item",       name="nullius-geothermal-plant-1",       quantity=1},
            {type="item",       name="nullius-grid-battery-1",           quantity=11},
            {type="item",       name="nullius-fusion-cell",              quantity=1},
            {type="item",       name="nullius-breeder-cell",             quantity=1},
            {type="item",       name="nullius-fission-cell",             quantity=1},
            {type="item",       name="nullius-antimatter",               quantity=1},

            {type="item",       name="nullius-geology-pack",             quantity=1000, next="x10"},
            {type="item",       name="nullius-climatology-pack",         quantity=1000, next="x10"},
            {type="item",       name="nullius-mechanical-pack",          quantity=1000, next="x10"},
            {type="item",       name="nullius-electrical-pack",          quantity=1000, next="x10"},
            {type="item",       name="nullius-chemical-pack",            quantity=1000, next="x10"},
            {type="item",       name="nullius-physics-pack",             quantity=1000, next="x10"},
            {type="item",       name="nullius-astronomy-pack",           quantity=1000, next="x10"},

            {type="item",       name="nullius-biochemistry-pack",        quantity=1000, next="x10"},
            {type="item",       name="nullius-microbiology-pack",        quantity=1000, next="x10"},
            {type="item",       name="nullius-botany-pack",              quantity=1000, next="x10"},
            {type="item",       name="nullius-nematology-pack",          quantity=1000, next="x10"},
            {type="item",       name="nullius-dendrology-pack",          quantity=1000, next="x10"},
            {type="item",       name="nullius-ichthyology-pack",         quantity=1000, next="x10"},
            {type="item",       name="nullius-zoology-pack",             quantity=1000, next="x10"},

            {type="kill",       name="character",                        quantity=1},
        }
    },


    ["Seablock"] = {
        required_mods = {"bobplates", "bobelectronics", "bobtech", "angelsbioprocessing", "SeaBlock"},
        milestones = {
            {type="item",       name="landfill",                       quantity=1},

            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="science-pack-gold",              quantity=1},
            {type="item",       name="advanced-logistic-science-pack", quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},
            {type="item",       name="token-bio",                      quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},

            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},

            {type="fluid",      name="gas-methane",                    quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="sulfur",                         quantity=1},
            {type="fluid",      name="liquid-sulfuric-acid",           quantity=1},
            {type="fluid",      name="liquid-resin",                   quantity=1},
            {type="item",       name="solid-paper",                    quantity=1},

            {type="item",       name="rocket-fuel",                    quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="antron",                         quantity=1},

            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="crystal-full-harmonic",          quantity=1},

            {type="item",       name="automation-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="science-pack-gold",              quantity=1000, next="x10"},
            {type="item",       name="advanced-logistic-science-pack", quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",        quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",           quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",             quantity=1000, next="x10"},

            {type="kill",       name="character",                      quantity=1, next="x5"},
        }
    },
    

    ["Pyanodon's Mods (Without AlienLife)"] = {
        required_mods = {"pycoalprocessing", "pyfusionenergy", "pyindustry", "pypetroleumhandling"},
        milestones = {
            {type="item",       name="flask",                         quantity=1},
            {type="item",       name="fawogae-substrate",             quantity=1},
            {type="item",       name="automation-science-pack",       quantity=1},

            {type="item",       name="alien-sample01",                quantity=1},
            {type="item",       name="lab-instrument",                quantity=1},
            {type="item",       name="logistic-science-pack",         quantity=1},
            {type="item",       name="military-science-pack",         quantity=1},

            {type="item",       name="optical-fiber",                 quantity=1},
            {type="item",       name="nexelit-plate",                 quantity=1},
            {type="item",       name="advanced-circuit",              quantity=1},
            {type="item",       name="rubber",                        quantity=1},
            {type="item",       name="stainless-steel",               quantity=1},
            {type="item",       name="tinned-cable",                  quantity=1},
            {type="item",       name="chemical-science-pack",         quantity=1},

            {type="item",       name="coated-container",              quantity=1},
            {type="item",       name="control-unit",                  quantity=1},
            {type="item",       name="nuclear-sample",                quantity=1},
            {type="item",       name="production-science-pack",       quantity=1},

            {type="item",       name="kevlar",                        quantity=1},
            {type="item",       name="volumetric-capacitor",          quantity=1},
            {type="item",       name="hyperelastic-material",         quantity=1},
            {type="item",       name="intelligent-unit",              quantity=1},
            {type="item",       name="nano-wires",                    quantity=1},
            {type="item",       name="nems",                          quantity=1},
            {type="item",       name="parametric-oscilator",          quantity=1},
            {type="item",       name="superconductor-servomechanims", quantity=1},
            {type="item",       name="super-steel",                   quantity=1},
            {type="item",       name="utility-science-pack",          quantity=1},

            {type="item",       name="nv-center",                     quantity=1},
            {type="item",       name="pi-josephson-junction",         quantity=1},
            {type="item",       name="quantum-dots",                  quantity=1},
            {type="item",       name="quantum-vortex-storage-system", quantity=1},
            {type="item",       name="var-josephson-junction",        quantity=1},
            {type="fluid",      name="liquid-helium",                 quantity=1},
            {type="fluid",      name="vacuum",                        quantity=1},
            {type="item",       name="space-science-pack",            quantity=1},
            
            {type="item",       name="locomotive",                    quantity=1},
            {type="item",       name="ht-locomotive",                 quantity=1},
            {type="item",       name="py-construction-robot-01",      quantity=1},
            {type="item",       name="py-construction-robot-02",      quantity=1},
            {type="item",       name="construction-robot-ht",         quantity=1},
            {type="item",       name="spidertron",                    quantity=1},

            {type="item",       name="automation-science-pack",       quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",       quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",            quantity=1000, next="x10"},

            {type="kill",       name="character",                     quantity=1, next="x5"},
        }
    },


    ["Pyanodon's Mods"] = {
        required_mods = {"pycoalprocessing", "pyfusionenergy", "pyindustry", "pypetroleumhandling", "pyalienlife"},
        milestones = {
            {type="item",       name="flask",                         quantity=1},
            {type="item",       name="fawogae-substrate",             quantity=1},
            {type="item",       name="automation-science-pack",       quantity=1},

            {type="item",       name="alien-sample01",                quantity=1},
            {type="item",       name="lab-instrument",                quantity=1},
            {type="item",       name="logistic-science-pack",         quantity=1},
            {type="item",       name="military-science-pack",         quantity=1},

            {type="item",       name="optical-fiber",                 quantity=1},
            {type="item",       name="nexelit-plate",                 quantity=1},
            {type="item",       name="alien-sample-02",               quantity=1},
            {type="item",       name="advanced-circuit",              quantity=1},
            {type="item",       name="rubber",                        quantity=1},
            {type="item",       name="stainless-steel",               quantity=1},
            {type="item",       name="tinned-cable",                  quantity=1},
            {type="item",       name="chemical-science-pack",         quantity=1},
                        
            {type="item",       name="plastic-bar",                   quantity=1},
            {type="item",       name="neuroprocessor",                quantity=1},
            {type="item",       name="moss",                          quantity=1},
            {type="item",       name="solidified-sarcorus",           quantity=1},
            {type="item",       name="paragen",                       quantity=1},
            {type="fluid",      name="flavonoids",                    quantity=1},
            {type="item",       name="py-science-pack",               quantity=1},

            {type="item",       name="coated-container",              quantity=1},
            {type="item",       name="control-unit",                  quantity=1},
            {type="item",       name="nuclear-sample",                quantity=1},
            {type="item",       name="alien-enzymes",                 quantity=1},
            {type="item",       name="small-parts-03",                quantity=1},
            {type="item",       name="production-science-pack",       quantity=1},

            {type="item",       name="perfect-samples",               quantity=1},
            {type="item",       name="volumetric-capacitor",          quantity=1},
            {type="item",       name="hyperelastic-material",         quantity=1},
            {type="item",       name="intelligent-unit",              quantity=1},
            {type="item",       name="nano-wires",                    quantity=1},
            {type="item",       name="nems",                          quantity=1},
            {type="item",       name="parametric-oscilator",          quantity=1},
            {type="item",       name="superconductor-servomechanims", quantity=1},
            {type="item",       name="super-steel",                   quantity=1},
            {type="item",       name="utility-science-pack",          quantity=1},

            {type="item",       name="strangelets",                   quantity=1},
            {type="item",       name="destablilized-toxirus",         quantity=1},
            {type="item",       name="nv-center",                     quantity=1},
            {type="item",       name="pi-josephson-junction",         quantity=1},
            {type="item",       name="quantum-dots",                  quantity=1},
            {type="item",       name="quantum-vortex-storage-system", quantity=1},
            {type="item",       name="var-josephson-junction",        quantity=1},
            {type="item",       name="yellow-cake",                   quantity=1},
            {type="fluid",      name="liquid-helium",                 quantity=1},
            {type="fluid",      name="vacuum",                        quantity=1},
            {type="item",       name="space-science-pack",            quantity=1},

            {type="item",       name="locomotive",                    quantity=1},
            {type="item",       name="ht-locomotive",                 quantity=1},
            {type="item",       name="py-construction-robot-01",      quantity=1},
            {type="item",       name="py-construction-robot-02",      quantity=1},
            {type="item",       name="construction-robot-ht",         quantity=1},
            {type="item",       name="spidertron",                    quantity=1},

            {type="item",       name="automation-science-pack",       quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",         quantity=1000, next="x10"},
            {type="item",       name="py-science-pack",               quantity=1000, next="x10"},
            {type="item",       name="production-science-pack",       quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",          quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",            quantity=1000, next="x10"},

            {type="kill",       name="character",                     quantity=1, next="x5"},
        }
    },


    ["Industrial Revolution 2"] = {
        required_mods = {"IndustrialRevolution"},
        milestones = {
            {type="item",       name="automation-science-pack", quantity=1},
            {type="technology", name="ir2-bronze-milestone",    quantity=1},
            {type="technology", name="ir2-glass-milestone",     quantity=1},
            {type="item",       name="logistic-science-pack",   quantity=1},
            {type="technology", name="ir2-iron-milestone",      quantity=1},
            {type="item",       name="military-science-pack",   quantity=1},
            {type="item",       name="chemical-science-pack",   quantity=1},
            {type="technology", name="ir2-gold-milestone",      quantity=1},
            {type="technology", name="ir2-lead-milestone",      quantity=1},
            {type="technology", name="ir2-nickel-milestone",    quantity=1},
            {type="technology", name="ir2-steel-milestone",     quantity=1},
            {type="item",       name="production-science-pack", quantity=1},
            {type="technology", name="ir2-chromium-milestone",  quantity=1},
            {type="technology", name="ir2-stainless-milestone", quantity=1},
            {type="technology", name="ir2-tellurium-milestone", quantity=1},
            {type="item",       name="utility-science-pack",    quantity=1},
            {type="technology", name="rocket-silo",             quantity=1},
            {type="item",       name="rocket-part",             quantity=100},
            {type="item",       name="space-science-pack",      quantity=1},

            {type="item",       name="copper-ingot",            quantity=1},
            {type="item",       name="tin-ingot",               quantity=1},
            {type="item",       name="bronze-ingot",            quantity=1},
            {type="item",       name="glass",                   quantity=1},
            {type="item",       name="iron-ingot",              quantity=1},
            {type="item",       name="gold-ingot",              quantity=1},
            {type="item",       name="nickel-ingot",            quantity=1},
            {type="item",       name="lead-ingot",              quantity=1},
            {type="item",       name="steel-ingot",             quantity=1},
            {type="item",       name="invar-ingot",             quantity=1},
            {type="item",       name="cupronickel-ingot",       quantity=1},
            {type="item",       name="chromium-ingot",          quantity=1},
            {type="item",       name="tellurium-ingot",         quantity=1},
            {type="item",       name="stainless-ingot",         quantity=1},
            {type="item",       name="plastiglass",             quantity=1},
            {type="item",       name="electronic-circuit",      quantity=1},
            {type="item",       name="advanced-circuit",        quantity=1},
            {type="item",       name="processing-unit",         quantity=1},

            {type="item",       name="steambot",                quantity=1},
            {type="item",       name="construction-robot",      quantity=1},
            {type="item",       name="locomotive",              quantity=1},
            {type="item",       name="monowheel",               quantity=1},
            {type="item",       name="car",                     quantity=1},
            {type="item",       name="tank",                    quantity=1},
            {type="item",       name="spidertron",              quantity=1},

            {type="item",       name="steam-engine",            quantity=1},
            {type="item",       name="solar-panel",             quantity=1},
            {type="item",       name="solar-array",             quantity=1},
            {type="item",       name="uranium-fuel-cell",       quantity=1},

            {type="item",       name="automation-science-pack", quantity=1000, next="x10"},
            {type="item",       name="logistic-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="military-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="chemical-science-pack",   quantity=1000, next="x10"},
            {type="item",       name="production-science-pack", quantity=1000, next="x10"},
            {type="item",       name="utility-science-pack",    quantity=1000, next="x10"},
            {type="item",       name="space-science-pack",      quantity=1000, next="x10"},

            {type="kill",       name="medium-biter",            quantity=1},
            {type="kill",       name="big-biter",               quantity=1},
            {type="kill",       name="behemoth-biter",          quantity=1},
            {type="kill",       name="character",               quantity=1, next="x5"},
        }
    },
}
