presets = {
    ["Vanilla"] = {
        required_mods = {},
        milestones = {
            {type="item",       name="automation-science-pack", quantity=1},
            {type="item",       name="logistic-science-pack",   quantity=1},
            {type="item",       name="locomotive",              quantity=1},
            {type="item",       name="military-science-pack",   quantity=1},
            {type="fluid",      name="petroleum-gas",           quantity=1},
            {type="item",       name="chemical-science-pack",   quantity=1},
            {type="item",       name="construction-robot",      quantity=1},
            {type="item",       name="production-science-pack", quantity=1},
            {type="item",       name="utility-science-pack",    quantity=1},
            {type="technology", name="rocket-silo",             quantity=1},
            {type="item",       name="rocket-part",             quantity=100},
            {type="item",       name="space-science-pack",      quantity=1},
            {type="item",       name="spidertron",              quantity=1},
            {type="item",       name="uranium-fuel-cell",       quantity=1},
            {type="item",       name="solar-panel",             quantity=1},
            {type="item",       name="solar-panel",             quantity=10000},
            {type="item",       name="automation-science-pack", quantity=10000},
            {type="item",       name="logistic-science-pack",   quantity=10000},
            {type="item",       name="military-science-pack",   quantity=10000},
            {type="item",       name="chemical-science-pack",   quantity=10000},
            {type="item",       name="production-science-pack", quantity=10000},
            {type="item",       name="utility-science-pack",    quantity=10000},
            {type="item",       name="space-science-pack",      quantity=10000},
        }
    },

    
    ["Vanilla (Extended)"] = {
        required_mods = {},
        milestones = {
            {type="item",       name="automation-science-pack", quantity=1},
            {type="item",       name="logistic-science-pack",   quantity=1},
            {type="item",       name="military-science-pack",   quantity=1},
            {type="fluid",      name="petroleum-gas",           quantity=1},
            {type="item",       name="chemical-science-pack",   quantity=1},
            {type="item",       name="construction-robot",      quantity=1},
            {type="item",       name="production-science-pack", quantity=1},
            {type="item",       name="utility-science-pack",    quantity=1},
            {type="technology", name="rocket-silo",             quantity=1},
            {type="item",       name="rocket-part",             quantity=100},
            {type="item",       name="space-science-pack",      quantity=1},
            {type="item",       name="locomotive",              quantity=1},
            {type="item",       name="car",                     quantity=1},
            {type="item",       name="tank",                    quantity=1},
            {type="item",       name="spidertron",              quantity=1},
            {type="item",       name="uranium-fuel-cell",       quantity=1},
            {type="item",       name="solar-panel",             quantity=1},
            {type="item",       name="solar-panel",             quantity=1000},
            {type="item",       name="solar-panel",             quantity=10000},
            {type="item",       name="solar-panel",             quantity=100000},
            {type="item",       name="solar-panel",             quantity=1000000},
            {type="item",       name="automation-science-pack", quantity=1000},
            {type="item",       name="automation-science-pack", quantity=10000},
            {type="item",       name="automation-science-pack", quantity=100000},
            {type="item",       name="automation-science-pack", quantity=1000000},
            {type="item",       name="logistic-science-pack",   quantity=1000},
            {type="item",       name="logistic-science-pack",   quantity=10000},
            {type="item",       name="logistic-science-pack",   quantity=100000},
            {type="item",       name="logistic-science-pack",   quantity=1000000},
            {type="item",       name="military-science-pack",   quantity=1000},
            {type="item",       name="military-science-pack",   quantity=10000},
            {type="item",       name="military-science-pack",   quantity=100000},
            {type="item",       name="military-science-pack",   quantity=1000000},
            {type="item",       name="chemical-science-pack",   quantity=1000},
            {type="item",       name="chemical-science-pack",   quantity=10000},
            {type="item",       name="chemical-science-pack",   quantity=100000},
            {type="item",       name="chemical-science-pack",   quantity=1000000},
            {type="item",       name="production-science-pack", quantity=1000},
            {type="item",       name="production-science-pack", quantity=10000},
            {type="item",       name="production-science-pack", quantity=100000},
            {type="item",       name="production-science-pack", quantity=1000000},
            {type="item",       name="utility-science-pack",    quantity=1000},
            {type="item",       name="utility-science-pack",    quantity=10000},
            {type="item",       name="utility-science-pack",    quantity=100000},
            {type="item",       name="utility-science-pack",    quantity=1000000},
            {type="item",       name="space-science-pack",      quantity=10000},
            {type="item",       name="space-science-pack",      quantity=100000},
            {type="item",       name="space-science-pack",      quantity=1000000},
        }
    },


    ["Space Exploration (No Spoilers)"] = {
        required_mods = {"space-exploration"},
        milestones = {
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="se-cargo-rocket-section",      quantity=100},
            {type="technology", name="se-spaceship",                 quantity=1},
            {type="item",       name="se-vulcanite-block",           quantity=1},
            {type="item",       name="se-cryonite-rod",              quantity=1},
            {type="item",       name="se-vitamelange-roast",         quantity=1},
            {type="item",       name="se-beryllium-ingot",           quantity=1},
            {type="item",       name="se-iridium-ingot",             quantity=1},
            {type="item",       name="se-naquium-ingot",             quantity=1},
            {type="item",       name="se-rocket-science-pack",       quantity=1},
            {type="item",       name="se-significant-data",          quantity=1},
            {type="item",       name="se-astronomic-science-pack-1", quantity=1},
            {type="item",       name="se-astronomic-science-pack-2", quantity=1},
            {type="item",       name="se-astronomic-science-pack-3", quantity=1},
            {type="item",       name="se-astronomic-science-pack-4", quantity=1},
            {type="item",       name="se-biological-science-pack-1", quantity=1},
            {type="item",       name="se-biological-science-pack-2", quantity=1},
            {type="item",       name="se-biological-science-pack-3", quantity=1},
            {type="item",       name="se-biological-science-pack-4", quantity=1},
            {type="item",       name="se-energy-science-pack-1",     quantity=1},
            {type="item",       name="se-energy-science-pack-2",     quantity=1},
            {type="item",       name="se-energy-science-pack-3",     quantity=1},
            {type="item",       name="se-energy-science-pack-4",     quantity=1},
            {type="item",       name="se-material-science-pack-1",   quantity=1},
            {type="item",       name="se-material-science-pack-2",   quantity=1},
            {type="item",       name="se-material-science-pack-3",   quantity=1},
            {type="item",       name="se-material-science-pack-4",   quantity=1},
            {type="item",       name="se-deep-space-science-pack-1", quantity=1},
            {type="item",       name="se-deep-space-science-pack-2", quantity=1},
            {type="item",       name="se-deep-space-science-pack-3", quantity=1},
            {type="item",       name="se-deep-space-science-pack-4", quantity=1},
            {type="technology", name="se-spaceship-victory",         quantity=1},
            {type="item",       name="se-significant-data",          quantity=1000},
            {type="item",       name="se-significant-data",          quantity=10000},
            {type="item",       name="se-significant-data",          quantity=100000},
        }
    },
    

    ["Krastorio 2"] = {
        required_mods = {"Krastorio2"},
        milestones = {
            {type="item",       name="basic-tech-card",              quantity=1},
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="fluid",      name="mineral-water",                quantity=1},
            {type="item",       name="silicon",                      quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="rare-metals",                  quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="imersite-powder",              quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="ai-core",                      quantity=1},
            {type="item",       name="space-science-pack",           quantity=1},
            {type="item",       name="matter-tech-card",             quantity=1},
            {type="fluid",      name="matter",                       quantity=1},
            {type="item",       name="advanced-tech-card",           quantity=1},
            {type="item",       name="singularity-tech-card",        quantity=1},
            {type="item",       name="kr-intergalactic-transceiver", quantity=1},
            {type="item",       name="basic-tech-card",              quantity=10000},
            {type="item",       name="automation-science-pack",      quantity=10000},
            {type="item",       name="logistic-science-pack",        quantity=10000},
            {type="item",       name="military-science-pack",        quantity=10000},
            {type="item",       name="chemical-science-pack",        quantity=10000},
            {type="item",       name="production-science-pack",      quantity=10000},
            {type="item",       name="utility-science-pack",         quantity=10000},
            {type="item",       name="space-science-pack",           quantity=10000},
            {type="item",       name="matter-tech-card",             quantity=10000},
            {type="item",       name="advanced-tech-card",           quantity=10000},
            {type="item",       name="singularity-tech-card",        quantity=10000},
        }
    },


    ["Space Exploration + Krastorio 2 (No Spoilers)"] = {
        required_mods = {"space-exploration", "Krastorio2"},
        milestones = {
            {type="item",       name="basic-tech-card",              quantity=1},
            {type="item",       name="automation-science-pack",      quantity=1},
            {type="fluid",      name="petroleum-gas",                quantity=1},
            {type="item",       name="logistic-science-pack",        quantity=1},
            {type="item",       name="silicon",                      quantity=1},
            {type="item",       name="military-science-pack",        quantity=1},
            {type="item",       name="chemical-science-pack",        quantity=1},
            {type="item",       name="construction-robot",           quantity=1},
            {type="item",       name="production-science-pack",      quantity=1},
            {type="item",       name="utility-science-pack",         quantity=1},
            {type="item",       name="se-cargo-rocket-section",      quantity=100},
            {type="technology", name="se-spaceship",                 quantity=1},
            {type="item",       name="se-vulcanite-block",           quantity=1},
            {type="item",       name="se-cryonite-rod",              quantity=1},
            {type="item",       name="se-vitamelange-roast",         quantity=1},
            {type="item",       name="se-beryllium-ingot",           quantity=1},
            {type="item",       name="se-iridium-ingot",             quantity=1},
            {type="fluid",      name="mineral-water",                quantity=1},
            {type="item",       name="rare-metals",                  quantity=1},
            {type="item",       name="imersite-powder",              quantity=1},
            {type="item",       name="se-naquium-ingot",             quantity=1},
            {type="item",       name="se-rocket-science-pack",       quantity=1},
            {type="item",       name="space-science-pack",           quantity=1},
            {type="item",       name="se-significant-data",          quantity=1},
            {type="item",       name="se-astronomic-science-pack-1", quantity=1},
            {type="item",       name="se-astronomic-science-pack-2", quantity=1},
            {type="item",       name="se-astronomic-science-pack-3", quantity=1},
            {type="item",       name="se-astronomic-science-pack-4", quantity=1},
            {type="item",       name="se-biological-science-pack-1", quantity=1},
            {type="item",       name="se-biological-science-pack-2", quantity=1},
            {type="item",       name="se-biological-science-pack-3", quantity=1},
            {type="item",       name="se-biological-science-pack-4", quantity=1},
            {type="item",       name="se-energy-science-pack-1",     quantity=1},
            {type="item",       name="se-energy-science-pack-2",     quantity=1},
            {type="item",       name="se-energy-science-pack-3",     quantity=1},
            {type="item",       name="se-energy-science-pack-4",     quantity=1},
            {type="item",       name="se-material-science-pack-1",   quantity=1},
            {type="item",       name="se-material-science-pack-2",   quantity=1},
            {type="item",       name="se-material-science-pack-3",   quantity=1},
            {type="item",       name="se-material-science-pack-4",   quantity=1},
            {type="item",       name="se-deep-space-science-pack-1", quantity=1},
            {type="item",       name="se-deep-space-science-pack-2", quantity=1},
            {type="item",       name="se-deep-space-science-pack-3", quantity=1},
            {type="item",       name="se-deep-space-science-pack-4", quantity=1},
            {type="item",       name="ai-core",                      quantity=1},
            {type="item",       name="matter-tech-card",             quantity=1},
            {type="fluid",      name="matter",                       quantity=1},
            {type="item",       name="advanced-tech-card",           quantity=1},
            {type="item",       name="singularity-tech-card",        quantity=1},
            {type="item",       name="kr-intergalactic-transceiver", quantity=1},
            {type="technology", name="se-spaceship-victory",         quantity=1},
            {type="item",       name="se-significant-data",          quantity=1000},
            {type="item",       name="se-significant-data",          quantity=10000},
            {type="item",       name="se-significant-data",          quantity=100000},
        }
    },


    ["Bob's Mods (Without bobtech)"] = {
        required_mods = {"bobplates", "bobelectronics"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},
            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="antron",                         quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            {type="item",       name="automation-science-pack",        quantity=10000},
            {type="item",       name="logistic-science-pack",          quantity=10000},
            {type="item",       name="military-science-pack",          quantity=10000},
            {type="item",       name="chemical-science-pack",          quantity=10000},
            {type="item",       name="production-science-pack",        quantity=10000},
            {type="item",       name="utility-science-pack",           quantity=10000},
            {type="item",       name="space-science-pack",             quantity=10000},
        }
    },


    ["Bob's Mods"] = {
        required_mods = {"bobplates", "bobelectronics", "bobtech"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="science-pack-gold",              quantity=1},
            {type="item",       name="advanced-logistic-science-pack", quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},

            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},
            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="antron",                         quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            {type="item",       name="automation-science-pack",        quantity=10000},
            {type="item",       name="logistic-science-pack",          quantity=10000},
            {type="item",       name="military-science-pack",          quantity=10000},
            {type="item",       name="chemical-science-pack",          quantity=10000},
            {type="item",       name="science-pack-gold",              quantity=10000},
            {type="item",       name="advanced-logistic-science-pack", quantity=10000},
            {type="item",       name="production-science-pack",        quantity=10000},
            {type="item",       name="utility-science-pack",           quantity=10000},
            {type="item",       name="space-science-pack",             quantity=10000},
        }
    },


    ["Angel's Industries"] = {
        required_mods = {"angelsindustries"},
        milestones = {
            {type="item",       name="automation-science-pack",   quantity=1},
            {type="item",       name="logistic-science-pack",     quantity=1},
            {type="item",       name="locomotive",                quantity=1},
            {type="item",       name="angels-construction-robot", quantity=1},
            {type="item",       name="military-science-pack",     quantity=1},
            {type="fluid",      name="gas-methane",               quantity=1},
            {type="item",       name="plastic-bar",               quantity=1},
            {type="item",       name="chemical-science-pack",     quantity=1},
            {type="item",       name="construction-robot",        quantity=1},
            {type="item",       name="sulfur",                    quantity=1},
            {type="fluid",      name="liquid-sulfuric-acid",      quantity=1},
            {type="item",       name="production-science-pack",   quantity=1},
            {type="item",       name="utility-science-pack",      quantity=1},
            {type="item",       name="rocket-fuel",               quantity=1},
            {type="technology", name="rocket-silo",               quantity=1},
            {type="item",       name="rocket-part",               quantity=100},
            {type="item",       name="space-science-pack",        quantity=1},
            {type="item",       name="angels-crawler",            quantity=1},
            {type="item",       name="spidertron",                quantity=1},
            {type="item",       name="uranium-fuel-cell",         quantity=1},
            {type="item",       name="solar-panel",               quantity=1},
            {type="item",       name="automation-science-pack",   quantity=10000},
            {type="item",       name="logistic-science-pack",     quantity=10000},
            {type="item",       name="military-science-pack",     quantity=10000},
            {type="item",       name="chemical-science-pack",     quantity=10000},
            {type="item",       name="production-science-pack",   quantity=10000},
            {type="item",       name="utility-science-pack",      quantity=10000},
            {type="item",       name="space-science-pack",        quantity=10000},
        }
    },


    ["Bob's and Angel's Mods"] = {
        required_mods = {"bobplates", "bobelectronics", "bobtech", "angelsindustries"},
        milestones = {
            {type="item",       name="automation-science-pack",        quantity=1},
            {type="item",       name="logistic-science-pack",          quantity=1},
            {type="item",       name="military-science-pack",          quantity=1},
            {type="item",       name="chemical-science-pack",          quantity=1},
            {type="item",       name="science-pack-gold",              quantity=1},
            {type="item",       name="advanced-logistic-science-pack", quantity=1},
            {type="item",       name="production-science-pack",        quantity=1},
            {type="item",       name="utility-science-pack",           quantity=1},
            {type="item",       name="space-science-pack",             quantity=1},
 
            {type="item",       name="electronic-circuit",             quantity=1},
            {type="item",       name="advanced-circuit",               quantity=1},
            {type="item",       name="processing-unit",                quantity=1},
            {type="item",       name="advanced-processing-unit",       quantity=1},

            {type="item",       name="bronze-alloy",                   quantity=1},
            {type="item",       name="invar-alloy",                    quantity=1},
            {type="item",       name="brass-alloy",                    quantity=1},
            {type="item",       name="silver-plate",                   quantity=1},
            {type="item",       name="gold-plate",                     quantity=1},
            {type="item",       name="aluminium-plate",                quantity=1},
            {type="item",       name="cobalt-steel-alloy",             quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="silicon-nitride",                quantity=1},
            {type="item",       name="titanium-plate",                 quantity=1},
            {type="item",       name="tungsten-plate",                 quantity=1},
            {type="item",       name="copper-tungsten-alloy",          quantity=1},
            {type="item",       name="tungsten-carbide",               quantity=1},
            {type="item",       name="nitinol-alloy",                  quantity=1},

            {type="fluid",      name="gas-methane",                    quantity=1},
            {type="item",       name="plastic-bar",                    quantity=1},
            {type="item",       name="sulfur",                         quantity=1},
            {type="fluid",      name="liquid-sulfuric-acid",           quantity=1},
            {type="fluid",      name="liquid-resin",                   quantity=1},
            {type="item",       name="solid-paper",                    quantity=1},

            {type="item",       name="rocket-fuel",                    quantity=1},
            {type="technology", name="rocket-silo",                    quantity=1},
            {type="item",       name="rocket-part",                    quantity=100},
            
            {type="item",       name="angels-construction-robot",      quantity=1},
            {type="item",       name="construction-robot",             quantity=1},
            {type="item",       name="locomotive",                     quantity=1},
            {type="item",       name="angels-crawler",                 quantity=1},
            {type="item",       name="antron",                         quantity=1},

            {type="item",       name="uranium-fuel-cell",              quantity=1},
            {type="item",       name="angels-thorium-fuel-cell",       quantity=1},
            {type="item",       name="angels-deuterium-fuel-cell",     quantity=1},
            {type="item",       name="solar-panel",                    quantity=1},
            {type="item",       name="crystal-full-harmonic",          quantity=1},

            {type="item",       name="automation-science-pack",        quantity=10000},
            {type="item",       name="logistic-science-pack",          quantity=10000},
            {type="item",       name="military-science-pack",          quantity=10000},
            {type="item",       name="chemical-science-pack",          quantity=10000},
            {type="item",       name="science-pack-gold",              quantity=10000},
            {type="item",       name="advanced-logistic-science-pack", quantity=10000},
            {type="item",       name="production-science-pack",        quantity=10000},
            {type="item",       name="utility-science-pack",           quantity=10000},
            {type="item",       name="space-science-pack",             quantity=10000},
        }
    },
}
